### ISSUE TITLE
get_defensive_roll - to override or not

### ISSUE THREAD

**Issue by dogleft** [johnroge/misc#1]
For the get_defensive_roll() method, I did some research, and your approach appears to be more 'Pythonic' - defining the method where you need it and not worrying about a definition in the base class. See https://en.wikipedia.org/wiki/Duck_typing

My comment came from experience in more rigidly typed languages. For example, in C++, even if the parent would be always overridden, you would define a virtual or abstract method in the parent to enforce the derived classes to override the method. See "NotImplementedError" part of this post: https://stackoverflow.com/questions/4714136/how-to-implement-virtual-methods-in-python 
It seems a good description of how to do this enforcement in Python if you want that safeguard\documentation.

**Comment by johnroge** [comment]
def get_defensive_roll(self):
    raise NotImplemented
Has been added to the main Creature class, and character-specific defensive_rolls implemented in 
each creature class for future modifications (currently they are all either duplicates or near-duplicates of each other).
