### ISSUE TITLE
Wizard.Attack()

### ISSUE THREAD

**Issue by dogleft** [johnroge/misc#2]
Inside the wizard Attack() method, your code is calling a method on another object (creature), which creates a coupling between Wizard and creature. 
See: https://en.wikipedia.org/wiki/Coupling_%28computer_programming%29
The coupling you have created is OK since you've abstracted to calling parent methods (hiding the internal details of how the specific creature handles the blow). The coupling is still restrictive nonetheless - consider what it prevents you from doing in the future. This is a slightly advanced concept, but worth discussing. 

Further along, your code is making decision about how a battle works out. This is more elementary error in cohesion. See: https://en.wikipedia.org/wiki/Cohesion_(computer_science)
In general the wizard code should only do wizardy things. E.g. picking a spell and rolling dice. In a real game the DM would decide the outcome of a conflict not the wizard. Again this is a slightly advanced concept, but worth discussing. I suggest considering a DM class - or moving the DM logic into your main game loop. 

I think your Python code look OK in general. What's worth discussing is how you lay out your classes.

**Comment by johnroge** [comment]
Functions "battle" and "match" are now in the main program and decide the outcome of a given battle. 
Would like to sit down and discuss various updates to the classes as some point along with some general troubleshooting of some new features that have been added. Will create a few new bugs to track.
